language: java
dist: xenial
sudo: false
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: mavaze-github
    token:
      secure: oOLIooZtzskKNjzEp9gvlxu2rIQmAlyfNB15WuXbK0BD5PSC18+bxVJzDPMF82AGdZIEN1V0/S65W5jGZRc6azZDBosSZPz+uWirD+1Cn1T88U7zvoRMBymBmJ2ufI+snZpmWtpwatMFMorsm/MSxY/3IEKcI2LM/sRhFonQAtf3sNvFzeE/1YzV/AGGy7JIpGHOfLSJ8R77dg56mLc/Y6mmL9ldVNH0kchYqvg5goQPet1OGEdw3Rll3Z2MGxYyrs6ggZO8zmbJ2R9w7f5KfHV6K8sbhhkzA8svPJ9kprpCWh9ZjG+ojiGyqAOfzjOZ6kyuWqeg0zhfj3WeoRr4nRRISLscxY52BPemDWLm1EH0GHbFMg1M226YnuLZDA7kH6VI84vB080BrCS6UjYoufw/6sH1Fmla6BGJ2YIhj+k71zptLEeGyqByY5rcO3H789NodOBKZZFqJV5j/AgkG+EDSz+MhxH9CpL3K9D/ALJFM7PNtdP00qb/lY06V9UftPGjh+3iOwN7vKMAdasrFws7ansJxZhIaWP1SZ8fNFuu1ul9JtTNLDzq3cEFh2uNpq/GU/XxTt9IbzVNhKQBumblT27uqyWJIBOF3/d8IqFsmy6gQAnx2hBe4t9wpaeUhyyNnxk4D0QIxAODje3bIw/+cfg4tZ3o62NnVZhCnrs=
install: true
script:
- mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent sonar:sonar
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
    secure: MyH//HQv8THQ06d7L/PYwp3A/93SRvRs2egZeGPTWxg17hLdflh0MWdxkf0WyRQYCH1EUfsPMCtw5Q98Hx1EvLGWJyCJ4wz4ifYnX6iW6L191gQSEj2GSGSyWPwaHCeAmwfYgcUnisvRBEYmPJtE0BJngpIlGPSNvOaSaswZdo6gufuZWdt4YiN4YBfIEZ3Y/vjdejSKXnkKK1E0ri2edzBnbCqaUdep9t88eG8CmVudBCWCnVIuc+84kSdCe33KEf8dMeI0LdD/mFjUCruro3u9rnVB11Gefab0EoHr7d7zRH7lIYkvWF0f0pBBP1ciWWnMAesYDjpEtx0aOUG/IDNuzs9SXrI5v+smNYSMmg51i/L+HbTbVsN05XsyoFdyXMLsgqI5FKqqJrXfsmO6k3/drEGXrtMcM25mqpAAFB+KGoylXu/RTJdLCwEqC1dvSTAUsTsIc2+XR7fBAq7SnovK5b8c6DBCKstULBGgILYVRGXW803wlSBnqDltnGW6h9I/ASIAr4EKWHw9OFuhhJOmbpZuF+g1Thu2KDMog/+RFesyjnFwEWW4mzqOkIkAzycNdsPQnZWUK1WDcAhYhq8eYuEuf6GFyHjerE5v6XXxt6YsWeME4fx3RX3QXUQ6tzxm5ffNZMERn1e/hy9hK3ffOC2uQee0iwJKmQ1uRJQ=
